Models/Menu_ViewComponent.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Quiz.Models
{
    public class Menu_ViewComponent : ViewComponent
    {
        private readonly DataAccess dataAccess = new DataAccess();

        public async Task<IViewComponentResult> InvokeAsync()
        {
            int Id_User = Convert.ToInt32(HttpContext.Session.GetInt32("User_Id"));
            // HttpContext.Session.GetInt32("Id_Mandant");
            bool DB_Admin = Convert.ToBoolean(HttpContext.Session.GetString("User_Admin"));

            if (Id_User == 17705 || Id_User == 17214)
            {
                DB_Admin = true;
            }

            var menu = new List<Parent_Menu>();
            menu = await dataAccess.GetMenu(DB_Admin);

            return View("Menu_Partial", menu);
        }
    }
}

Controllers/UserPagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Quiz.Models;
using ReflectionIT.Mvc.Paging;

namespace Quiz.Controllers
{
    /// <summary>
    /// Controller that's responsible for all "User's Pages"
    /// </summary>
    public class UserPagesController : Controller
    {
        DataAccess dataAccess = new DataAccess();
        Helper helper = new Helper();

        /// <summary>
        /// Calls Training list page
        /// </summary>
        /// <param name="filter">Word we're looking for</param>
        /// <param name="page">Page number</param>
        /// <param name="sortExpression">Sets order by specific column</param>
        /// <returns>Training list page with available trainings for specific user</returns>
        public async Task<IActionResult> Trainings_List(string filter, int page = 1, string sortExpression = "Id")
        {
            if (HttpContext.Session.GetInt32("User_Id") == null)
            {
                return RedirectToAction("Index", "Home");
            }
            //if (HttpContext.Session.GetString("training") == "training")
            //{
            //    int Id_Campaign = Convert.ToInt32(HttpContext.Session.GetInt32("Id_Campaign"));
            //    int Id_Presentation = Convert.ToInt32(HttpContext.Session.GetInt32("Id_Presentation"));
            //    HttpContext.Session.Remove("Id_Campaign");
            //    HttpContext.Session.Remove("Id_Presentation");
            //    return RedirectToAction("Training_Page", "PresentationPages", new { Id_Campaign, Id_Presentation });
            //}
            else
            {
                HttpContext.Session.Remove("test");
                int Id_User = Convert.ToInt32(HttpContext.Session.GetInt32("User_Id"));
                //HttpContext.Session.SetInt32("Campaign_Id", id);

                var campaigns = new List<Training_Campaign>();
                campaigns = await dataAccess.AvailableTrainings(Id_User);

                foreach (var camp in campaigns)
                {
                    camp.Start_Date = camp.Start_Date.Replace("00:00:00", "").TrimEnd();
                    camp.End_Date = camp.End_Date.Replace("23:59:59", "").TrimEnd();

                    foreach (var pres in camp.Presentations)
                    {
                        Tuple<string, double, int, string, string> result = dataAccess.GetUserPoints(camp.Id, pres.Id, Id_User);

                        pres.User_Points = result.Item1;
                        pres.Points_Percentage = result.Item2;
                        pres.Attempt_Date = result.Item4;
                        pres.Attempts_Left = camp.Attempts - result.Item3;
                        pres.Author_Name = result.Item5;
                    }
                }

                if (!string.IsNullOrWhiteSpace(filter))
                {
                    campaigns = campaigns.Where(c => c.Name.ToLower().Contains(filter.ToLower()) || c.Presentations[0].Name.ToLower().Contains(filter.ToLower())).ToList();
                }

                var model = PagingList.Create(campaigns, 4, page, sortExpression, "Id");

                model.RouteValue = new RouteValueDictionary {
                         { "filter", filter}
            };

                if (HttpContext.Session.GetString("Error") == null)
                {
                    ViewBag.Error = null;
                    ViewBag.Msg = null;
                }
                else
                {
                    ViewBag.Error = HttpContext.Session.GetString("Error");
                    ViewBag.Msg = HttpContext.Session.GetString("Msg");
                    HttpContext.Session.Remove("Error");
                    HttpContext.Session.Remove("Msg");
                }
                return View(model);
            }
        }

        /// <summary>
        /// Retrieves all test results for specific user
        /// </summary>
        /// <param name="campaign">Training campaign object</param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult Get_All_Results([FromBody] Training_Campaign campaign)
        {
            int Id_User = Convert.ToInt32(HttpContext.Session.GetInt32("User_Id"));

            var presentations = dataAccess.GetAllResults(campaign.Id, campaign.Presentations[0].Id, Id_User);

            return Json(presentations);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Start Page</title>

    <link rel="apple-touch-icon" sizes="180x180" href="~/favicon_io/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/favicon_io/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/favicon_io/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">

    @*<environment include="Development">
                <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            </environment>
            <environment exclude="Development">
                <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
                      asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                      asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
                      crossorigin="anonymous"
                      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
            </environment>

        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
        <!-- Bootstrap core CSS -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
        <!-- Material Design Bootstrap -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.2/css/mdb.min.css" rel="stylesheet">

    *@
    <link rel="stylesheet" href="~/lib/fontawesome-free-5.11.2-web/css/all.css" />
    <!-- Material Design Bootstrap -->
    <link rel="stylesheet" href="~/lib/MDB-Free_4.8.8/css/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/MDB-Free_4.8.8/css/mdb.css" />
    <!-- Clock font -->
    @*<link href='https://fonts.googleapis.com/css?family=Orbitron' rel='stylesheet' type='text/css'>*@
    <link href='~/lib/w3.css/Orbitron.css' rel='stylesheet' type='text/css'>


    <!-- My CSS -->
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

</head>
<body>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>



    @*<environment include="Development">
                <script src="~/lib/jquery/dist/jquery.js"></script>
                <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
            </environment>
            <environment exclude="Development">
                <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                        asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                        asp-fallback-test="window.jQuery"
                        crossorigin="anonymous"
                        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
                </script>
                <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                        asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                        asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                        crossorigin="anonymous"
                        integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
                </script>
            </environment>

        <!-- JQuery -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <!-- Bootstrap tooltips -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
        <!-- Bootstrap core JavaScript -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <!-- MDB core JavaScript -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.2/js/mdb.min.js"></script>

    *@

    <!-- JQuery -->
    <script type="text/javascript" src="~/lib/MDB-Free_4.8.8/js/jquery-3.4.1.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="~/lib/MDB-Free_4.8.8/js/popper.min.js"></script>
    @*<script type="text/javascript" src="~/lib/fontawesome-free-5.11.2-web/js/all.js"></script>*@

    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="~/lib/MDB-Free_4.8.8/js/bootstrap.min.js"></script>

    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="~/lib/MDB-Free_4.8.8/js/mdb.min.js"></script>


    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout_Admin.cshtml
@using Microsoft.AspNetCore.Http;


@{ string hoverStyle = "";
    string collapse = "";
    string rotate = "";
    var handlingController = this.ViewContext.RouteData.Values["controller"].ToString();
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>@ViewData["Title"]</title>

    <link rel="apple-touch-icon" sizes="180x180" href="~/favicon_io/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/favicon_io/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/favicon_io/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/lib/fontawesome-free-5.11.2-web/css/all.css" />
    <!-- Material Design Bootstrap -->
    <link rel="stylesheet" href="~/lib/MDB-Free_4.8.8/css/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/MDB-Free_4.8.8/css/mdb.css" />
    <!-- MDBootstrap Datatables  -->
    <link href="~/lib/MDB-Free_4.8.8/css/addons/datatables.min.css" rel="stylesheet">
    <!-- Data Picker -->
    <link rel="stylesheet" type="text/css" href="~/lib/DataPicker/daterangepicker.css" />
    <!-- w3schools CSS -->
    <link rel="stylesheet" href="~/lib/w3.css/w3.css" />
    <link rel="stylesheet" href="~/lib/w3.css/Raleway.css" />
    @*<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">*@

    <!-- Select -->
    <link rel="stylesheet" href="~/lib/Select-BS/css/bootstrap-select.css">
    <!-- Admin_Layout -->
    <link rel="stylesheet" href="~/css/Admin_Layout.css" asp-append-version="true"/>
    @*<link rel="stylesheet" href="~/lib/w3.css/Raleway.css" />*@
    @{ 
        if (handlingController == "AnalyticsPages")
        {
            <link rel="stylesheet" href="~/css/Analytics.css" />
        }
    }
</head>
<body>

    <nav class="navbar navbar-lg navbar-dark fixed-top scrolling-navbar" style="z-index:4; background-color:rgb(241, 104, 7); min-height:50px;">
        <button class="navbar-toggler w3-bar-item w3-button w3-hide-large w3-hover-none w3-hover-text-light-grey" onclick="w3_open();"><i class="fa fa-bars"></i>  Menu</button>
        <strong style="font-family:Arial Black; font-size:large; color:white;">Let<span style="color: black;">Me</span>Repair </strong>

        @if (Context.Session.GetString("User_Admin") != "")
        {
            <a asp-area="" asp-controller="Home" asp-action="Logout" asp-route-id="@Context.Session.GetInt32("User_Id")" style="text-decoration:none;">
                <button class="btn btn-sm btn-dark font-weight-bold">Logout  &nbsp;&nbsp;&nbsp;<i class="fas fa-sign-out-alt"></i></button>
            </a>
        }

    </nav>

    <!-- Sidebar/menu -->
    <nav class="w3-sidebar w3-collapse w3-white w3-left" style="z-index:3; width:250px; margin-top:2px;" id="mySidebar">
        <br>
        <div class="w3-container w3-row">
            @*<div class="w3-col s4">
                    <img src="" class="w3-circle w3-margin-right" style="width:46px" alt="Photo">
                </div>*@
            <div class="w3-col s8 w3-bar" style="margin-top:10px;">
                <h5>Welcome, <strong>@Context.Session.GetString("User_First_Name")</strong></h5>
                @*<a href="#" class="w3-bar-item w3-button"><i class="fa fa-envelope"></i></a>
                    <a href="#" class="w3-bar-item w3-button"><i class="fa fa-user"></i></a>
                    <a href="#" class="w3-bar-item w3-button"><i class="fa fa-cog"></i></a>*@
            </div>
        </div>
        <hr>
        <div class="w3-container">
            <h3 id="Menu_Header">Menu</h3>
            <hr id="hr" />
        </div>

        <div class="w3-bar-block" style="font-size:1.1em;">
            <a href="#" class="w3-bar-item w3-button w3-padding-16 w3-hide-large w3-dark-grey w3-hover-black" onclick="w3_close()" title="close menu"><i class="fas fa-times"></i>  Close Menu</a>

            @await Component.InvokeAsync("Menu_")

            @*<a asp-area="" asp-controller="UserPages" asp-action="Trainings_List" class="w3-bar-item w3-button w3-padding  @if (ViewData["Title"].ToString()  == "Trainings") {@hoverStyle }"><i class="fas fa-list-alt"></i>  Trainings List</a>*@


            <a asp-area="" asp-controller="Home" asp-action="Logout" asp-route-id="@Context.Session.GetInt32("User_Id")" class="w3-bar-item w3-button w3-padding"><i class="fas fa-sign-out-alt"></i>  Logout</a>
            <br><br>
        </div>
    </nav>
    <!-- Overlay effect when opening sidebar on small screens -->
    <div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>
    <!-- !PAGE CONTENT! -->
    <div class="w3-main" style="margin-left:250px;margin-top:43px;">
        <!-- Header -->
        <header class="w3-container" style="padding-top:22px; background-color:rgba(160,160,160,0.7)">
            @if (Context.Session.GetString("User_Admin") == "True")
            {
                <h5><i class="fas fa-tachometer-alt"></i><b>&nbsp; Supervisor's Dashboard</b></h5>
            }
            else
            {
                <h5><i class="fas fa-tachometer-alt"></i><b>&nbsp; User's Dashboard</b></h5>
            }
        </header>
        <div class="container-fluid" id="container_fluid1">
            <partial name="_CookieConsentPartial" />
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
        <!-- End page content -->
    </div>

    <!-- JQuery -->
    <script type="text/javascript" src="~/lib/MDB-Free_4.8.8/js/jquery-3.4.1.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="~/lib/MDB-Free_4.8.8/js/popper.min.js"></script>
    @*<script type="text/javascript" src="~/lib/fontawesome-free-5.11.2-web/js/all.js"></script>*@

    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="~/lib/MDB-Free_4.8.8/js/bootstrap.min.js"></script>

    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="~/lib/MDB-Free_4.8.8/js/mdb.min.js"></script>
    <!-- JavaScript 4 Date Range Picker -->
    <script type="text/javascript" src="~/lib/DataPicker/moment.min.js"></script>
    <script type="text/javascript" src="~/lib/DataPicker/daterangepicker.js"></script>
    <!-- MDBootstrap Datatables  -->
    <script type="text/javascript" src="~/lib/MDB-Free_4.8.8/js/addons/datatables.min.js"></script>
    <script type="text/javascript" src="~/js/Data_Table.js"></script>

    <!-- Select -->
    <script src="~/lib/Select-BS/js/bootstrap-select.min.js"></script>
    @if (handlingController == "AnalyticsPages")
    {

        <script type="text/javascript" src="~/lib/amcharts4/core.js"></script>
        <script type="text/javascript" src="~/lib/amcharts4/charts.js"></script>
        <script type="text/javascript" src="~/lib/amcharts4/themes/material.js"></script>
        <script type="text/javascript" src="~/lib/amcharts4/themes/dark.js"></script>
        <script type="text/javascript" src="~/lib/amcharts4/themes/animated.js"></script>
        <script type="text/javascript" src="~/lib/amcharts4/lang/en_US.js"></script>

        <script type="text/javascript" src="~/js/Analytics.js"></script>

    }

    <script src="~/js/Admin_Layout.js" asp-append-version="true"></script>


    @RenderSection("Scripts", required: false)

</body>
</html>

Views/Shared/_Layout_Material.cshtml
@using Microsoft.AspNetCore.Http;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Start Page</title>

    <link rel="apple-touch-icon" sizes="180x180" href="~/favicon_io/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/favicon_io/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/favicon_io/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    @*
        <environment include="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        </environment>
        <environment exclude="Development">
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
                  crossorigin="anonymous"
                  integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
        </environment>

        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
        <!-- Bootstrap core CSS -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
        <!-- Material Design Bootstrap -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.2/css/mdb.min.css" rel="stylesheet">
    *@
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/lib/fontawesome-free-5.11.2-web/css/all.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">

    <!-- Material Design Bootstrap -->
    <link rel="stylesheet" href="~/lib/MDB-Free_4.8.8/css/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/MDB-Free_4.8.8/css/mdb.css" />

    <link rel="stylesheet" href="~/css/Material_Layout.css" asp-append-version="true"/>

</head>
<body>
    <!-- Main navigation -->
    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top scrolling-navbar">
        <div class="container">
            <a class="navbar-brand" href="http://10.1.2.105/opal/Login.aspx">
                <strong style="font-family:Arial Black; font-size:xx-large;">Let<span style="color: black;">Me</span>Repair </strong>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-7" aria-controls="navbarSupportedContent-7" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent-7">
                <ul class="navbar-nav mr-auto"></ul>
                <ul class="navbar-nav nav-flex-icons">
                    <li class="nav-item">

                        @if (@Context.Session.GetString("User_Admin") != "" && @Context.Session.GetString("User_Admin") != null)
                        {
                            <a asp-area="" asp-controller="Home" asp-action="Logout" asp-route-id="@Context.Session.GetInt32("User_Id")" style="text-decoration:none;">
                                <button class="btn btn-dark font-weight-bold">Logout  &nbsp;<i class="fas fa-sign-out-alt"></i></button>
                            </a>
                        }

                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Full Page Intro -->

    @{
        string domainName = Context.Request.PathBase.ToString();
    }
    <div class="view" style="background-image:url(@domainName/images/training.jpg);">
        <!-- Mask & flexbox options-->
        <div class="mask rgba-gradient d-flex justify-content-center align-items-center">
            <!-- Content -->

            <div class="container">
                <partial name="_CookieConsentPartial" />
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>

        </div>
        <!-- Mask & flexbox options-->
    </div>
    @*
        <!-- JS -->
        <environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
            </script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
            </script>
        </environment>

        <!-- JQuery -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <!-- Bootstrap tooltips -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
        <!-- Bootstrap core JavaScript -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <!-- MDB core JavaScript -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.2/js/mdb.min.js"></script>
    *@

    @*<script type="text/javascript" src="~/lib/fontawesome-free-5.11.2-web/js/all.js"></script>*@

    <!-- JQuery -->
    <script type="text/javascript" src="~/lib/MDB-Free_4.8.8/js/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="~/lib/MDB-Free_4.8.8/js/popper.min.js"></script>

    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="~/lib/MDB-Free_4.8.8/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="~/lib/MDB-Free_4.8.8/js/mdb.min.js"></script>


    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>